### ISSUE TITLE
Invia e ricevi SOCKETS?

### ISSUE THREAD

**Issue by gerrydoro** [LorenzoGodi/Android-Simple-Socket-App#1]
Sul readme.md l'app viene definita con questa frase
"Invia e ricevi sockets TCP in Android Oreo 8.1" 
ma la frase sembra priva di senso, cosa s'intende per _invio e ricezione di sockets_?

**Comment by LorenzoGodi** [comment]
Ciao. Ho già risolto con l'ultimo commit. Chiedo scusa per la svista

**Comment by gerrydoro** [comment]
Grazie, non ti preoccupare. La community di GitHub non è qui per offendere o creare disagi
